In [12]:
from selenium import webdriver
from time import sleep
import pandas as pd
url = "https://www.census.gov/construction/bps/uspermits.html?fbclid=IwAR02DAW5FBC-At1R0g8qV_kFxrry7aIK5l1lfb--XDCLehPDUIlQ6r0lz8c"

# Driver setting
options = webdriver.ChromeOptions()
prefs = {'profile.default_content_settings.popups': 0, 'download.default_directory': '.'}
options.add_experimental_option('prefs', prefs)

#用chromedriver開啟Chrome
driver = webdriver.Chrome(chrome_options=options)
driver.get(url)

# Find excel and download
excel_data = driver.find_element_by_xpath("//a[@href='/construction/nrc/xls/permits_cust.xls']").click()

sleep(5)
driver.close()

/Users/jyun/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: DeprecationWarning: use options instead of chrome_options
  if sys.path[0] == '':

In [61]:
# Save into dataframe form , the number 2 implies "sheet 2"(where the Seasonally adjusted data saved)
df_SA = pd.read_excel('permits_cust.xls', 2)
# date
col2 = df_SA[df_SA.columns[0]]
# total value
col3 = df_SA[df_SA.columns[1]]

df_UA = pd.read_excel('permits_cust.xls', 1)
col1 = df_UA[df_UA.columns[1]]

# new list for date
date = []
# Seasonally Adjusted Annual Rate
SA_value = []
UA_value = []
# Data starts from row 8 to row 716 (1960-1-1 to 2019-1-1 = 12*59+1 = 709 = 716 - 8 + 1)
# Save into list
for i in range(8,717):
    date.append(col2[i])
    SA_value.append(col3[i])
    UA_value.append(col1[i+12])
# From list to dataframe
value_dict = {"Date":date, "PermitsUA" : UA_value,"PermitsSA": SA_value}
value_df = pd.DataFrame(value_dict)
value_df.set_index(keys= ["Date"],inplace=True)
# Finally we have
value_df.head(20)

            PermitsUA  PermitsSA
Date
1960-01-01       62.6       1092
1960-02-01       68.1       1088
1960-03-01       89.0        955
1960-04-01      101.1       1016
1960-05-01      103.4       1052
1960-06-01       94.8        958
1960-07-01       86.3        999
1960-08-01       93.7        994
1960-09-01       84.9        984
1960-10-01       81.6        972
1960-11-01       73.9        979
1960-12-01       58.7        951
1961-01-01       59.7        969
1961-02-01       58.8        961
1961-03-01       92.7       1000
1961-04-01       94.0       1002
1961-05-01      105.3       1027
1961-06-01      104.5       1070
1961-07-01       92.8       1083
1961-08-01      108.6       1159